#!/usr/bin/env bash
# MemStack v3.3.1 — PreCompact Hook
# Auto-saves a diary snapshot before CC context compaction
# Always exit 0 — must never block compaction
#
# Triggered by: PreCompact hook event

set -uo pipefail

# --- Config ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
DIARY_DIR="$SCRIPT_DIR/../diary"
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)
TIMESTAMP="${DATE}T${TIME}"
OUTFILE="$DIARY_DIR/${DATE}-compaction.md"

mkdir -p "$DIARY_DIR"

# --- Gather context ---

# Project name
PROJECT_NAME=$(basename "$PROJECT_DIR")

# Current branch
BRANCH=$(git -C "$PROJECT_DIR" branch --show-current 2>/dev/null || echo "unknown")

# Uncommitted changes (staged + unstaged, compact)
UNCOMMITTED=$(git -C "$PROJECT_DIR" status --short 2>/dev/null || echo "unable to read git status")
if [ -z "$UNCOMMITTED" ]; then
    UNCOMMITTED="None — working tree clean"
fi

# Last 5 commits (for context on what was being worked on)
RECENT_COMMITS=$(git -C "$PROJECT_DIR" log --oneline -5 2>/dev/null || echo "no commits available")

# Recent bash history (last 5 commands from shell history)
BASH_HISTORY=""
if [ -f "$HOME/.bash_history" ]; then
    BASH_HISTORY=$(tail -5 "$HOME/.bash_history" 2>/dev/null || echo "unavailable")
elif [ -f "$HOME/.zsh_history" ]; then
    BASH_HISTORY=$(tail -5 "$HOME/.zsh_history" 2>/dev/null | sed 's/^[^;]*;//' || echo "unavailable")
else
    BASH_HISTORY="no history file found"
fi

# Recently modified files (last 10 minutes, likely what was being edited)
RECENT_FILES=$(find "$PROJECT_DIR" -maxdepth 4 \
    -not -path '*/.git/*' \
    -not -path '*/node_modules/*' \
    -not -path '*/.claude/diary/*' \
    -newer "$PROJECT_DIR/.git/HEAD" \
    -type f 2>/dev/null | head -10 || echo "unable to detect")

if [ -z "$RECENT_FILES" ]; then
    RECENT_FILES="None detected"
fi

# --- Check for existing compaction entry today (append if so) ---
if [ -f "$OUTFILE" ]; then
    # Append a separator and new entry
    cat >> "$OUTFILE" <<ENTRY

---

## Compaction Snapshot — ${TIME}

**COMPACTION INTERRUPTED** — Context was compacted mid-session. Information below captures state at the moment of compaction.

### Uncommitted Changes
\`\`\`
${UNCOMMITTED}
\`\`\`

### Recent Commits
\`\`\`
${RECENT_COMMITS}
\`\`\`

### Recent Shell Commands
\`\`\`
${BASH_HISTORY}
\`\`\`

### Recently Modified Files
\`\`\`
${RECENT_FILES}
\`\`\`
ENTRY
else
    # Create new file
    cat > "$OUTFILE" <<ENTRY
---
type: compaction-diary
project: ${PROJECT_NAME}
date: ${DATE}
branch: ${BRANCH}
flag: COMPACTION_INTERRUPTED
---

# Compaction Diary — ${PROJECT_NAME} — ${DATE}

> Auto-generated by PreCompact hook. Context was compacted mid-session.
> Read this at session resume to recover lost context.

## Compaction Snapshot — ${TIME}

**COMPACTION INTERRUPTED** — Context was compacted mid-session. Information below captures state at the moment of compaction.

### Uncommitted Changes
\`\`\`
${UNCOMMITTED}
\`\`\`

### Recent Commits
\`\`\`
${RECENT_COMMITS}
\`\`\`

### Recent Shell Commands
\`\`\`
${BASH_HISTORY}
\`\`\`

### Recently Modified Files
\`\`\`
${RECENT_FILES}
\`\`\`
ENTRY
fi

exit 0
